---
- name: Qemu domains on user session
  hosts: all
  roles:
    - role: gwerlas.libvirt
      vars:
        libvirt_uri: qemu:///session

        libvirt_pools:
          - name: data-dir
            target:
              path: /home/molecule/images

        libvirt_domains:
          - name: my-node
            type: qemu
            memory: 128M
            cpu:
              mode: custom
            disks:
              - name: os
              - name: data
                capacity: 2G
                target: vdb
                pool: data-dir
            interfaces:
              - type: user
