---
- name: Set directives in {{ _libvirt_conf.key }}
  ansible.builtin.lineinfile:
    path: /etc/libvirt/{{ _libvirt_conf.key }}.conf
    line: >-
      {{ _libvirt_directive.key }} = {{
        ('"' ~ _libvirt_directive.value ~ '"') if _libvirt_directive.value is string
        else (_libvirt_directive.value | int) if _libvirt_directive.value is boolean
        else _libvirt_directive.value
      }}
    regexp: "^#?\\s*{{ _libvirt_directive.key }}\\s*="
    create: true
    mode: "0644"
  with_dict: "{{ _libvirt_conf.value }}"
  loop_control:
    loop_var: _libvirt_directive
  notify: Restart libvirt service
