---
- name: Networks - List
  community.libvirt.virt_net:
    command: facts
    uri: "{{ libvirt_uri }}"

- name: Networks - Create
  community.libvirt.virt_net:
    name: "{{ _libvirt_network.name }}"
    xml: "{{ lookup('template', 'network.xml.j2') }}"
    command: define
    uri: "{{ libvirt_uri }}"
  loop: |
    {{
      (
        (_libvirt_networks | selectattr('state', 'undefined'))
      + (_libvirt_networks | selectattr('state', 'defined') | selectattr('state', '!=', 'absent'))
      ) | rejectattr('name', 'in', ansible_facts.libvirt_networks)
    }}
  loop_control:
    loop_var: _libvirt_network

- name: Networks - Update the list
  community.libvirt.virt_net:
    command: facts
    uri: "{{ libvirt_uri }}"

- name: Network - Autostart
  community.libvirt.virt_net:
    name: "{{ _libvirt_network.name }}"
    autostart: "{{ _libvirt_network.autostart | default(true) }}"
    uri: "{{ libvirt_uri }}"
  loop: |
    {{
      (
        (_libvirt_networks | selectattr('state', 'undefined'))
      + (_libvirt_networks | selectattr('state', 'defined') | selectattr('state', '!=', 'absent'))
      )
    }}
  loop_control:
    loop_var: _libvirt_network

- name: Network - Status
  community.libvirt.virt_net:
    name: "{{ _libvirt_network.name }}"
    state: "{{ _libvirt_network.state | default('active') }}"
    uri: "{{ libvirt_uri }}"
  loop: "{{ _libvirt_networks }}"
  loop_control:
    loop_var: _libvirt_network
