---
- name: Load variables
  when: system_wide is undefined
  ansible.builtin.import_tasks: vars.yml

- name: Networks
  when: libvirt_networks | length > 0
  ansible.builtin.import_tasks: networks.yml
  vars:
    networks: "{{ libvirt_networks }}"

- name: Storage pools
  when: libvirt_pools | length > 0
  ansible.builtin.import_tasks: pools.yml
  vars:
    pools: "{{ libvirt_pools }}"

- name: Volumes
  when: volumes_computed | length > 0
  ansible.builtin.import_tasks: volumes.yml
  vars:
    volumes: "{{ volumes_computed }}"

- name: Domains
  when: libvirt_domains | length > 0
  ansible.builtin.import_tasks: domains.yml
  vars:
    domains: "{{ libvirt_domains }}"
