---
- name: Load variables
  when: _libvirt_runs_system_wide is undefined
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/facts.yml"

- name: Networks
  when: libvirt_networks | length > 0
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/networks.yml"
  vars:
    _libvirt_networks: "{{ libvirt_networks }}"

- name: Storage pools
  when: libvirt_pools | length > 0
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/pools.yml"

- name: Volumes
  when: _libvirt_volumes_to_create | length > 0
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/volumes.yml"

- name: Domains
  when: libvirt_domains | length > 0
  ansible.builtin.import_tasks: "{{ role_path }}/tasks/domains.yml"
  vars:
    _libvirt_domains: "{{ libvirt_domains }}"
