---
- name: Services - DNSMasq
  when: dnsmasq_management_method == 'disable'
  become: true
  ansible.builtin.service:
    name: dnsmasq
    state: stopped
    enabled: false

- name: Services - DNSMasq
  when: dnsmasq_management_method == 'bind'
  become: true
  notify: Restart dnsmasq service
  block:
    - name: Services - DNSMasq bind interfaces
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        line: bind-interfaces
        regexp: '^#?bind-interfaces'
        mode: "0644"
       
    - name: Services - DNSMasq ethernet interfaces
      ansible.builtin.lineinfile:
        path: /etc/dnsmasq.conf
        line: interface={{ interface }}
        insertafter: '^#?interface='
        mode: "0644"
      loop: |
        {{
          ansible_interfaces |
          map('replace', '-', '_') |
          reject('search', '^vnet') |
          map('extract', ansible_facts) |
          selectattr('type', 'in', libvirt_dnsmasq_interface_types) |
          map(attribute='device')
        }}
      loop_control:
        loop_var: interface

- name: Services - Enable and start
  when: ansible_service_mgr != 'systemd'
  become: true
  ansible.builtin.service:
    name: "{{ service }}"
    state: started
    enabled: true
  loop:
    - dbus
    - libvirtd
  loop_control:
    loop_var: service

- name: Services - Systemd
  when: ansible_service_mgr == 'systemd'
  block:
    - name: Services - Get the libvirtd version
      environment:
        PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin
      ansible.builtin.command:
        cmd: libvirtd -V
      register: result
      changed_when: false
      check_mode: false

    - name: Services - Register the libvirtd version
      ansible.builtin.set_fact:
        libvirtd_version: "{{ result.stdout | split(' ') | last }}"

    - name: Services - Systemd legacy
      when:
        - libvirtd_version is version('5.6.0', '<')
      ansible.builtin.systemd:
        name: libvirtd.service
        state: started
        enabled: true

    - name: Services - Systemd
      when:
        - libvirtd_version is version('5.6.0', '>=')
      ansible.builtin.systemd:
        name: "{{ socket }}"
        state: started
        enabled: true
      loop:
        - libvirt-guests.service
        - libvirtd.socket
        - virtlockd.socket
        - virtlogd.socket
      loop_control:
        loop_var: socket
