---
- name: Variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ vars_file }}"
        - empty.yml
      paths:
        - vars
  loop:
    - "{{ ansible_os_family | lower }}-like.yml"                                          # debian-like,  redhat-like, etc.
    - "{{ ansible_distribution | lower }}.yml"                                            # debian,       fedora,      ubuntu
    - "{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}-like.yml"  # redhat7-like
    - "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml"    # debian10
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml" # ubuntu-bionic
    - "{{ libvirt_backend }}.yml"                                                         # qemu
  loop_control:
    loop_var: vars_file
  register: result

- name: Variables
  ansible.builtin.debug:
    var: result
    verbosity: 1

- name: Facts
  ansible.builtin.set_fact:
    cacheable: true
    libvirt_packages: "{{ packages_computed }}"
