---
- name: Provision libvirt with any users allowed to use it
  hosts: all
  roles:
    - role: gwerlas.system
      vars:
        system_packages_upgrade: true

    - role: gwerlas.libvirt
      vars:
        libvirt_users: []
