---
- name: Converge
  hosts: all
  roles:
    - role: gwerlas.libvirt
      vars:
        libvirt_domains:
          - name: my-node
            type: qemu
            memory: 128M
            cpu:
              mode: custom
            disks:
              - name: os
              - name: data
                format: raw
                source: /dev/vdb
                target: vdb
                type: block
            networks:
              - name: default
