---
dependency:
  name: galaxy
lint: ansible-lint
driver:
  name: vagrant
  provider:
    name: libvirt
  provision: true
platforms:
  - name: archlinux
    box: archlinux/archlinux
    provider_raw_config_args: &raw_config
      - "cpu_mode = 'host-passthrough'"
      - "disk_bus = 'virtio'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "pacman -Syu --noconfirm git net-tools python3 sudo unzip which"'
  - name: gentoo
    box: generic/gentoo
    cpus: 4
    memory: 8192
    provider_raw_config_args:
      - "cpu_mode = 'host-passthrough'"
      - "nic_model_type = 'virtio'"
      - "video_type = 'virtio'"
      - "disk_driver :cache => 'writeback'"
      - "storage :file, bus: 'virtio', cache: 'writeback'"

  # Debian like
  - name: debian11
    groups:
      - debian
    box: debian/bullseye64
    provider_raw_config_args: *raw_config
  - name: debian12
    groups:
      - debian
    box: debian/bookworm64
    provider_raw_config_args: *raw_config
  - name: ubuntu2004
    groups:
      - debian
      - ubuntu
    box: generic/ubuntu2004
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: ubuntu2204
    groups:
      - debian
      - ubuntu
    box: generic/ubuntu2204
    memory: 4096
    provider_raw_config_args: *raw_config
  - name: ubuntu2210
    groups:
      - debian
      - ubuntu
    box: generic/ubuntu2210
    memory: 4096
    provider_raw_config_args: *raw_config

  # RedHat like
  - name: centos7
    groups:
      - el
    box: centos/7
    provider_raw_config_args: *raw_config
  - name: alma8
    groups:
      - el
    box: almalinux/8
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: alma9
    groups:
      - el
    box: almalinux/9
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: fedora36
    groups:
      - el
      - fedora
    box: generic/fedora36
    memory: 2048
    provider_raw_config_args: *raw_config
  - name: fedora37
    groups:
      - el
      - fedora
    box: generic/fedora37
    memory: 2048
    provider_raw_config_args: *raw_config
provisioner:
  name: ansible
verifier:
  name: ansible
