---
- name: Become superuser
  become: true
  block:
    - name: Qemu - Security driver
      when: libvirt_security_driver | bool
      ansible.builtin.lineinfile:
        path: /etc/libvirt/qemu.conf
        line: 'security_driver = "{{ libvirt_security_driver }}"'
        regexp: '^#?security_driver\s*='
        mode: "0644"
      vars:
        libvirt_security_driver: |-
          {% if ansible_facts.apparmor.status | default('') == 'enabled' %}apparmor
          {%- elif ansible_facts.selinux.mode | default('') in ['enforcing', 'permissive'] %}selinux
          {%- endif %}
      notify: Restart libvirt service

    - name: Qemu - Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Qemu - Default network
      when: |
        libvirt_active_default_network
        or 
        libvirt_remove_default_network
      ansible.builtin.import_tasks: "{{ role_path }}/tasks/networks.yml"
      vars:
        libvirt_uri: qemu:///system
        networks:
          - name: default
            state: "{{ 'active' if libvirt_active_default_network else 'absent' }}"
            autostart: true
            forward:
              mode: nat
            bridge:
              name: virbr0
            ips:
              - address: 192.168.122.1
                netmask: 255.255.255.0
                dhcp:
                  ranges:
                    - start: 192.168.122.2
                      end: 192.168.122.254

    - name: Default pool
      ansible.builtin.import_tasks: "{{ role_path }}/tasks/pools.yml"
      vars:
        libvirt_uri: qemu:///system
        libvirt_pools:
          - name: default
            type: dir
            target:
              path: /var/lib/libvirt/images
              permissions:
                owner: "{{ libvirt_system_users.qemu }}"
                group: "{{ libvirt_system_groups.qemu }}"
